### PR TITLE
Added Plexon's SiNAPS probe definitions.

### PR DESCRIPTION
**Pull request by nikhilchandra**
I have added Plexon's probe definitions for five SiNAPS probes:

1S256 -- this is a 1-shank probe with 256 channels arranged in 2 columns.
1S512 -- this is a 1-shank probe with 512 channels arranged in 2 columns.
1S512-N -- this is a 1-shank probe with 512 channels arranged in 4 columns, intended for non-human primates.
4S1024 - this is a 4-shank probe with 1,024 channels (256 channels per shank). For each shank, channels are arranged in 2 columns.
8S1024 - this is an 8-shank probe with 1,024 channels (128 channels per shank). For each shank, channels are arranged in 2 columns.

### CODE REVIEW

**Comment by nikhilchandra** [comment]
Hi @alejoe91 I hope you are well. I hope I did everything correctly for adding definitions for SiNAPS probes to Probe Interface Library?

**Comment by nikhilchandra** [comment]
Looks like there was an extra property "device_channel_indices" that wasn't supposed to be there. I have removed it.

**Comment by alejoe91** [comment]
Indeed. Actually in the case of Sinaps I think it's ok that device channel.indices is specified in the json, since the probes are pre-wired and wiring cannot be changed. @nikhilchandra I'll make a separate PR to fix the validation because I think it makes more sense here.

@samuelgarcia @zm11 do you guys agree?

Then you can add back the device_channel_indices (but let's wait for Sam's and Zach's feedback)

**Comment by nikhilchandra** [comment]
I'm not sure if the device channel indices are even required. So far as I know there is no "rewiring" of channels that takes place between the probe and the base station.

**Comment by nikhilchandra** [comment]
@alejoe91 is this ready for merging?

**Review by alejoe91 — APPROVED** [review]

**Comment by alejoe91** [comment]
Wiring was removed. The probes are not switchable, bust still I think that wiring should be added when reading the file/processing the data

**Pull request merged**
